# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zbyněk Šlajchrt's Tech Blog
tagline:             "Articles about Scala, Java, BigData etc..."
url:                 http://zslajchrt.github.io/
paginate:            10
baseurl:             "http://zslajchrt.github.io/"

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Zbyněk Šlajchrt
  url:               http://zslajchrt.github.io
  email:             zslajchrt@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/zslajchrt
